# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            OMKAR PATHAK
tagline:          ''
description:      'Software Developer by Profession, <br /> Pythonista by &hearts;'
url:              http://www.omkarpathak.in
baseurl:          /

author:
  name:           'Omkar Pathak'
  url:            https://twitter.com/omkarpathak27

paginate:         5
paginate_path: 	  /blog/page:num/

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/OmkarPathak/omkarpathak.github.io
  
plugins:
    - jekyll-feed
    - jekyll-redirect-from
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-avatar
    - jemoji
    - jekyll-mentions
    - jekyll-paginate

twitter_username: omkarpathak27
github_username: OmkarPathak
linkedin_username: omkar-pathak-94473811b
facebook_username: omkarpathak27
quora_username: Omkar-Pathak-18 
instagram_username: omkarpathak27

